### PR TITLE
Make sure `/tmp/log` dir exists

### LINKED ISSUE #42: `BrefKernel` should make sure `/tmp/log` dir exists
Symfony `about` console command displays info about log directory. If executed in Lambda with pre-warmed cache, it fails with `Error thrown while running command "about". Message: "RecursiveDirectoryIterator::__construct(/tmp/log): failed to open dir: No such file or directory"` error.

The relevant parts in the command are https://github.com/symfony/symfony/blob/db321016cc/src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php#L87 and https://github.com/symfony/symfony/blob/db321016cc/src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php#L115-L120

The code assumes that the log dir always exist, which is true for a standard Symfony application – `Kernel::buildContainer()` creates the dir if needed: https://github.com/symfony/symfony/blob/db321016cc693d7155042918c667fdaa2d5f72bc/src/Symfony/Component/HttpKernel/Kernel.php#L634-L642

However, if the app is pre-warmed before deploying to AWS, `Kernel::buildContainer()` doesn't get called in Lambda, `/tmp/log` isn't created and `about` command fails.

There are probably more ways how to make sure the log dir exists, but I feel like it's something `BrefKernel` should take care of.

### PR DESCRIPTION
**Pull request by vhenzl**
Resolves #42.

### CODE REVIEW

File: src/BrefKernel.php [hunk 1]
```diff
@@ -122,6 +123,24 @@ protected function prepareCacheDir(string $readOnlyDir, string $writeDir): void
...
+    protected function ensureLogDir(string $writeLogDir): void
+    {
+        if (! $this->isLambda() || is_dir($writeLogDir)) {
+            return;
+        }
+
+        $filesystem = new Filesystem;
+        $filesystem->mkdir($writeLogDir);
+
+        $this->logToStderr('Symfony log directory created.');
```
Comment (t-richard) [inline src/BrefKernel.php:141]: Not sure this is useful logs

**Review by t-richard — CHANGES_REQUESTED** [review]
Thanks for starting this! 

Just a minor comment.

Could you also add tests that tries to write to the log dir directly ? I'd say one in an http context and one in a console context. 

We had some differences in the past between the lifecycle of the Kernel in console and in http, so better be on the safe side of things 🙂

You can take a look at existing tests, they already do that (run the console and http request).

File: src/BrefKernel.php [hunk 2]
```diff
@@ -122,6 +123,24 @@ protected function prepareCacheDir(string $readOnlyDir, string $writeDir): void
         ));
     }
 
+    /**
+     * Even though applications should never write into it on Lambda, there are parts of Symfony
+     * (like "about" CLI command) that expect the log dir exists, so we have to make sure of it.
+     *
+     * @see https://github.com/brefphp/symfony-bridge/issues/42
```
Comment (mnapoli) [inline src/BrefKernel.php:130]: Awesome thanks for the comment, that makes maintenance much easier!

File: src/BrefKernel.php [hunk 3]
```diff
@@ -122,6 +123,24 @@ protected function prepareCacheDir(string $readOnlyDir, string $writeDir): void
...
+     */
+    protected function ensureLogDir(string $writeLogDir): void
```
Comment (mnapoli) [inline src/BrefKernel.php:132]:
```suggestion
    private function ensureLogDir(string $writeLogDir): void
```

If we make it protected, then it's part of the API of this package and we can't have BC break on this. I'd rather not expose anything we don't have to.

File: src/BrefKernel.php [hunk 4]
```diff
@@ -122,6 +123,24 @@ protected function prepareCacheDir(string $readOnlyDir, string $writeDir): void
...
+    {
+        if (! $this->isLambda() || is_dir($writeLogDir)) {
```
Comment (mnapoli) [inline src/BrefKernel.php:134]:
```suggestion
        if (is_dir($writeLogDir) || ! $this->isLambda()) {
```

I _think_ `is_dir()` is faster to run, so it might be better to call this one first (that way if the directory exists, it will skip the next test).

File: src/BrefKernel.php (hunk 1 above)
Comment (mnapoli) [reply src/BrefKernel.php:141]: Same, I think we can remove this line to avoid any noise.

**Review by mnapoli — COMMENTED** [review]
On top of @t-richard's comment about tests, I've added minor feedback.

Thanks a lot for taking the time to fix this!

File: src/BrefKernel.php (hunk 3 above)
Comment (vhenzl) [reply src/BrefKernel.php]: I went with the same visibility as `prepareCacheDir()` has, but yeah, makes sense.

File: src/BrefKernel.php (hunk 4 above)
Comment (vhenzl) [reply src/BrefKernel.php:134]: I don't know. But if, then the same is probably true for the condition in `prepareCacheDir()`…

Comment (t-richard) [reply src/BrefKernel.php:134]: Really not sure about performance impact here. But we're not talking about compute heavy things in either case, `isLambda` is just a string comparison with a environment variable.

Comment (t-richard) [reply src/BrefKernel.php:134]: And just for fun, I made a very naive benchmark and apparently `is_dir` is slower. Not to be taken as a scientific measure though, but `isLambda` would be around a 100 times faster than `is_dir`.

See https://3v4l.org/d4ILY#v8.0.8

File: tests/Functional/LogDirTest.php [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+    {
+        (new Filesystem)->remove(self::LOCAL_TMP_DIRECTORY . '/log');
+    }
+
+    public function test Symfony works(): void
+    {
+        $this->assertCommandIsSuccessful($this->runHttpRequest());
+    }
+
+    public function test log dir created in tmp on http request(): void
```
Comment (t-richard) [inline tests/Functional/LogDirTest.php:29]:
```suggestion
    public function test log dir is created in tmp on http request(): void
```

File: tests/Functional/LogDirTest.php [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+    {
+        $this->assertDirectoryNotExists(self::LOCAL_TMP_DIRECTORY . '/log');
+
+        $this->runHttpRequest();
+        $this->assertDirectoryExists(self::LOCAL_TMP_DIRECTORY . '/log');
+    }
+
+    public function test log dir created in tmp on console command(): void
```
Comment (t-richard) [inline tests/Functional/LogDirTest.php:37]:
```suggestion
    public function test log dir is created in tmp on console command(): void
```

**Review by t-richard — APPROVED** [review]
Just small naming things.

But it looks good to me, thanks @vhenzl !

File: src/BrefKernel.php (hunk 4 above)
Comment (mnapoli) [reply src/BrefKernel.php:134]: Good to know thanks!

**Comment by mnapoli** [comment]
Thank you @vhenzl and @t-richard!
